version: '3'

services:
    autoscaler:
        build:
            context: ..
            dockerfile: devstack/Dockerfile
        image: autoscaler
        volumes:
            - "../:/app"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/var/run/docker-cli.sock:/var/run/docker-cli.sock"
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
            - DEBUG=1
            - DOCKER_BUILD_PATH=/app
        env_file:
            - ../.env