name: pull-request-pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install application
        run: pip install -e .

      - name: Install linter
        run: pip install black flake8 mypy pydocstyle bandit[toml]

      - name: Check code style with black
        run: black --check src

      - name: Check lints with flake8
        run: flake8

      - name: Run static type checker
        run: mypy src

      - name: Check doc style
        run: pydocstyle src

      - name: Run security linter
        run: bandit -r -c pyproject.toml .